name: cosworth.racedatasystems.com
favicon: null
layout_spectrum: 0.45115
typography_spectrum: 0.64334
title: Cosworth at Race Data Systems
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e8ebf2'
    - '#000000'
    - '#3b363a'
    - '#6b6263'
    - '#bdb2b4'
  brandStrength: 0.5490336152724922
  lightness: 0.5625000018626451
  saturation: 0.625
  rhythmicContrast: 0.8802272018510848
purpose: []
